debug: false
logging:
  level:
    me.honki12345.hoonlog: debug
    org.springframework.web.server: debug
    org.springframework.security: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.orm.jdbc.bind: trace
spring:
  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  h2.console.enabled: true
  sql.init.mode: always
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB
      enabled: true
      location:

jwt:
  secretKey: ${JWT_SECRET_KEY}
  refreshKey: ${JWT_REFRESH_KEY}
file:
  upload:
    location: ${user.home}${file.separator}hoonlog
    url: /images/post/
  image:
    location: ${user.home}${file.separator}hoonlog${file.separator}post

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
jwt:
  secretKey: 098766543211hoon-log-secretKey-2023-10-0101234567890
  refreshKey: 2098766543211hoon023_10-01-hoon-log-refreshKey01234567890
file:
  upload:
    location: ${user.home}${file.separator}test-hoonlog
    url: /images/post/
  image:
    location: ${user.home}${file.separator}test-hoonlog${file.separator}post
