debug: false
logging:
  level:
    me.honki12345.hoonlog: debug
    org.springframework.web.server: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hoonlog
    username: fpg123
    password: password
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false
  h2.console.enabled: true
  sql.init.mode: always

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
